package com.usj.budgettracking.data

data class BudgetCategory(
    val id: Int? = null, // Primary key (auto-generated by SQLite)
    val name: String,    // Category name
    val budget: Double,  // Budget limit for the category
    var currentSpending: Double = 0.0 // Current spending in the category
)
